Allow replacing existing content using wagtail content import
torchbox/wagtail-content-import pull request #41
Opened 2021-07-12 13:05 UTC by kaedroho

2021-07-12 13:13 UTC, jacobtoppm commented
Hey @kaedroho, looking great! Will give this a thorough review soon, but just wanted to note that https://torchbox.github.io/wagtail-content-import/submitting_backend/ gives instructions on picker creation as part of it, so probably needs updating with this PR as well

2021-07-13 10:00 UTC, jacobtoppm requested changes
Looking good, just a few potential refactors + bits we should mention in the docs

2021-07-19 14:09 UTC, kaedroho commented on wagtail_content_import/utils.py
> +    has_unsaved_changes = False
It was ``False`` on create and wasn't sure why

2021-07-19 14:30 UTC, kaedroho commented on wagtail_content_import/utils.py
> +    has_unsaved_changes = False
Oh yes, good spot!

2021-07-19 14:30 UTC, kaedroho commented on wagtail_content_import/templates/wagtail_content_import/picker_buttons_edit.html
> +{% if default_picker %}
Updated

2021-07-19 14:34 UTC, kaedroho commented on wagtail_content_import/models.py
> +    def update_from_import(self, parsed_doc, user):
Updated

2021-07-27 13:07 UTC, jacobtoppm commented on wagtail_content_import/models.py
> +    def update_from_import(self, parsed_doc, user):
Thanks! What were your thoughts on:

> However, couldn't we share a fair bit between the two? Pretty much get rid of create, just create a blank instance, and just use the update_from_import instead? Feels like even if we have to make this an upgrade consideration, it should be easier to customise which fields are being imported into in one place

Ie have the creation and update methods share logic?

2021-07-27 13:10 UTC, jacobtoppm requested changes
Generally looking great!

- Just my remaining comment over sharing create/update logic to discuss
- A draft of how you'd like update considerations to be mentioned in release notes for custom pickers + however update logic ends up working (can be fairly quick, just for https://github.com/torchbox/wagtail-content-import/blob/master/docs/release_notes.md)

2021-07-30 11:23 UTC, kaedroho commented on wagtail_content_import/models.py
> +    def update_from_import(self, parsed_doc, user):
Sorry I missed this, yep I think that's a good idea. I'll have a go at implementing it!

2021-07-30 13:16 UTC, kaedroho commented
@jacobtoppm  how is this?

Feature: The import button has been added to the page editor on existing pages, allowing editors to update them with imported content.

Upgrade consideration: Picker trigger event

If you have created a custom picker, you should update the event that it uses to trigger it to open. Previously, pickers listened for the 'click' event on the import button but we have now added a new event called 'openPicker'.

For example:

```javascript
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('[data-content-import-picker="my_picker"]').forEach(function (element) {
            // ...

            element.addEventListener('click', function() {  // <----- Change this from 'click' to 'openPicker'
                // ...
            });
        });
    });
```

See: [Submitting a new backend](https://torchbox.github.io/wagtail-content-import/submitting_backend/)

Upgrade consideration: Customised ``.create_from_import()`` method

If you have customised the ``.create_from_import()`` method on any page, you should replace this with a customisation of ``.update_from_import()`` instead. This will allow your customisation to work when the page is being updated or created.

See: [Changing Import Fields](https://torchbox.github.io/wagtail-content-import/changing_import_fields/)

2021-08-03 09:33 UTC, jacobtoppm approved these changes
Looks great, thanks for making those changes! Release notes sound good as well

2021-08-03 09:33 UTC, merged