Wagtail 5 support
torchbox/wagtail-content-import pull request #59
Opened 2023-10-17 16:15 UTC by jams2

Adds support for Wagtail 5.

I have tested:
- OneDrive import
- Google import
- Local document import

2023-10-17 16:17 UTC, jams2 commented on wagtail_content_import/admin_views.py
> +        template_vars={},
Unrelated change, just improves readability.

2023-10-19 18:32 UTC, zerolab requested changes
Needs a couple of small changes. LGTM otherwise (caveat: haven't got a chance to test locally)

2023-10-20 09:10 UTC, jams2 commented on tox.ini
>      django4.1: Django>=4.1,<4.2
Fixed in https://github.com/torchbox/wagtail-content-import/pull/59/commits/92e62bd3d9f97e2e9fba463781954301a31b8418

2023-10-20 09:12 UTC, jams2 commented on tox.ini
> +    python{3.8,3.9,3.10}-django3.2-wagtail{4.1,4.2,5.0,5.1,main}-{sqlite,postgres}
Thanks, removed it in https://github.com/torchbox/wagtail-content-import/pull/59/commits/92e62bd3d9f97e2e9fba463781954301a31b8418 - this seems to be the simplest I can get it, due to:
- Django 3.2 not supporting Python 3.11; and
- Wagtail 4.1 not support Django 4.2.

2023-10-20 09:19 UTC, jams2 commented on tox.ini
> +    python{3.8,3.9,3.10}-django3.2-wagtail{4.1,4.2,5.0,5.1,main}-{sqlite,postgres}
Thanks, reshuffled this a bit in https://github.com/torchbox/wagtail-content-import/pull/59/commits/f45bfef78da467c67ffe7d39fce60ce6a24ba08f, it's a little easier on the eyes/brain.

2023-11-02 15:30 UTC, gasman commented on tox.ini
>      django4.1: Django>=4.1,<4.2
Nitpick - the commit message says 4.1 (which _isn't_ EOL yet as it's an LTS release), although it is indeed removing 4.2.

2023-11-02 15:31 UTC, gasman approved these changes
Other than the commit message nitpick, LGTM!

2023-11-02 15:38 UTC, jams2 commented on tox.ini
>      django4.1: Django>=4.1,<4.2
Thanks, reworded.

2023-11-02 15:50 UTC, merged